export enum displayScreensRouteKeys {
    InitialScreen = "InitialScreen",
    ActivityIndicatorScreen = "Activity Indicators",
    CustomButtonScreen = "Buttons",
    TextInputScreen = "Text Inputs",
    RadioButtonScreen = "Radio Buttons",
    SegmentedButtonScreen = "Segmented Buttons",
    ToggleButtonScreen = "Toggle Buttons",
    SwitchScreen = "Switch",
    DateScreen = "Date Pickers",
    TimeScreen = "Time Pickers",
    ChipScreen = "Chips",
    ModalScreen = "Modal",
    FAB = "FAB",
    Menu = "Menu",
    RegisterScreen = "RegisterScreen",
    FirebaseAnalaytics = "Analytics",
    Crashlytics = "Crashlytics",
    GoogleDrive = "GoogleDrive",
    SharePoint = "SharePoint",
}